### ISSUE TITLE
Creación de controladores

### ISSUE THREAD

**Issue by FernandoEmilianoFloresDeLaRiva** [FernandoEmilianoFloresDeLaRiva/Simulador-restaurante#9]
Realizar controladores y comunicarlos a la vistas 
- Controlador para recepcionista.
- Controlador para cliente.
- Controlador para mesero.
- Controlador para lista de comida.

**Comment by Rextro616** [comment]
Implementar Platform para renderización (UI) de hilos secundarios (controladores) con el metodo runLater()
